import type { Metadata } from "next";
import "./globals.css";
import TanstackProvider from "@/context/TanstackProvider";
import { PropsWithChildren } from "react";
import AntdProvider from "@/context/AntdProvider";
import RootLayout from "@/components/RootLayout";

export const metadata: Metadata = {
  title: "Goto",
  description: "Generated by create next app",
};

export default function PageLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <AntdProvider>
            <RootLayout>{children}</RootLayout>
          </AntdProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
