import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import RootLayout from "@/components/RootLayout";
import AntdProvider from "@/lib/Context/AntdProvider";
import AuthProvider from "@/lib/Context/AuthProvider";
import TanstackProvider from "@/lib/Context/TanstackProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Goto",
  description: "Generated by create next app",
};

export default async function PageLayout({ children }: PropsWithChildren) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <AntdProvider>
            <AuthProvider session={session}>
              <RootLayout>{children}</RootLayout>
            </AuthProvider>
          </AntdProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
