import type { Metadata } from "next";
import "./globals.css";
import TanstackProvider from "@/lib/Context/TanstackProvider";
import { PropsWithChildren } from "react";
import AntdProvider from "@/lib/Context/AntdProvider";
import RootLayout from "@/components/RootLayout";
import AuthProvider from "@/lib/Context/AuthProvider";

export const metadata: Metadata = {
  title: "Goto",
  description: "Generated by create next app",
};

export default function PageLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <AntdProvider>
            <AuthProvider>
              <RootLayout>{children}</RootLayout>
            </AuthProvider>
          </AntdProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
